"""create tables

Revision ID: 05fb4375cfa6
Revises: cab95922ecd6
Create Date: 2025-11-19 04:56:10.442614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fb4375cfa6'
down_revision = 'cab95922ecd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###