"""create tables

Revision ID: 0eadc4df5cf5
Revises: a223ada0c91e
Create Date: 2025-11-19 05:23:04.742841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eadc4df5cf5'
down_revision = 'a223ada0c91e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###