"""create tables

Revision ID: 2429f5f4a55e
Revises: cb1cf53f5a65
Create Date: 2025-11-19 01:29:41.955739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2429f5f4a55e'
down_revision = 'cb1cf53f5a65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###