"""create tables

Revision ID: 28c8e0641e07
Revises: 2429f5f4a55e
Create Date: 2025-11-19 01:33:51.334580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c8e0641e07'
down_revision = '2429f5f4a55e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###