"""create tables

Revision ID: 2bc7517ef153
Revises: 944a353b2f16
Create Date: 2025-11-19 01:08:26.799534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc7517ef153'
down_revision = '944a353b2f16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###