"""create tables

Revision ID: 30b5dc7e8283
Revises: 73ee3faab7f6
Create Date: 2025-11-19 03:36:34.801914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b5dc7e8283'
down_revision = '73ee3faab7f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###