"""create tables

Revision ID: 3e99c309a6d0
Revises: 6c3ac621bc1c
Create Date: 2025-11-19 02:55:48.337039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e99c309a6d0'
down_revision = '6c3ac621bc1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###