"""create tables

Revision ID: 412ecfa946f0
Revises: 28c8e0641e07
Create Date: 2025-11-19 01:35:07.202169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412ecfa946f0'
down_revision = '28c8e0641e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###