"""create tables

Revision ID: 431cf245c0b3
Revises: 2ebdf8308cd2
Create Date: 2025-11-19 01:40:54.862708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431cf245c0b3'
down_revision = '2ebdf8308cd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###