"""create tables

Revision ID: 491ffb0fcb27
Revises: 0eadc4df5cf5
Create Date: 2025-11-23 12:25:10.543661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491ffb0fcb27'
down_revision = '0eadc4df5cf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###