"""create tables

Revision ID: 5998237ad33e
Revises: a6c6931dcb18
Create Date: 2025-11-19 00:59:38.127351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5998237ad33e'
down_revision = 'a6c6931dcb18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###