"""create tables

Revision ID: 6c3ac621bc1c
Revises: a674e941a261
Create Date: 2025-11-19 02:37:12.533351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3ac621bc1c'
down_revision = 'a674e941a261'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###