"""create tables

Revision ID: 73ee3faab7f6
Revises: 5be539744b1b
Create Date: 2025-11-19 03:33:12.535722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ee3faab7f6'
down_revision = '5be539744b1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###