"""create tables

Revision ID: 944a353b2f16
Revises: 5998237ad33e
Create Date: 2025-11-19 01:04:06.534197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944a353b2f16'
down_revision = '5998237ad33e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###