"""create tables

Revision ID: a223ada0c91e
Revises: 05fb4375cfa6
Create Date: 2025-11-19 05:15:06.256760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a223ada0c91e'
down_revision = '05fb4375cfa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###