"""create tables

Revision ID: b16da1ebd8c0
Revises: 77d6bb17d16b
Create Date: 2025-11-18 06:11:09.491068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16da1ebd8c0'
down_revision = '77d6bb17d16b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###