"""create tables

Revision ID: c02f4222e544
Revises: dcedb74a9263
Create Date: 2025-11-19 02:11:58.812273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02f4222e544'
down_revision = 'dcedb74a9263'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###