"""create tables

Revision ID: cab95922ecd6
Revises: d840e13c093d
Create Date: 2025-11-19 04:54:47.466018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab95922ecd6'
down_revision = 'd840e13c093d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###