"""create tables

Revision ID: cb1cf53f5a65
Revises: d5b583457105
Create Date: 2025-11-19 01:27:44.714505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1cf53f5a65'
down_revision = 'd5b583457105'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###