"""create tables

Revision ID: d5b583457105
Revises: 2bc7517ef153
Create Date: 2025-11-19 01:12:54.420605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b583457105'
down_revision = '2bc7517ef153'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###