"""create tables

Revision ID: d840e13c093d
Revises: eeefc55fa9e0
Create Date: 2025-11-19 04:49:23.079508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd840e13c093d'
down_revision = 'eeefc55fa9e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###