"""create tables

Revision ID: eeefc55fa9e0
Revises: b8e1c23917a8
Create Date: 2025-11-19 04:45:25.379980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeefc55fa9e0'
down_revision = 'b8e1c23917a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###